// <auto-generated />
using System;
using GradDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103122239_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradDemo.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CashierId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("OrderId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillDate = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CashierId = 2,
                            OrderId = 1,
                            PaymentMethod = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            BillDate = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CashierId = 3,
                            OrderId = 2,
                            PaymentMethod = "Credit Card"
                        },
                        new
                        {
                            Id = 3,
                            BillDate = new DateTime(2024, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CashierId = 3,
                            OrderId = 4,
                            PaymentMethod = "Cash"
                        });
                });

            modelBuilder.Entity("GradDemo.Models.CancelledOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CancelledById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledById");

                    b.HasIndex("OrderId");

                    b.ToTable("CancelledOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CancelledById = 2,
                            CancelledDate = new DateTime(2024, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 5,
                            Reason = "Customer had to leave suddenly"
                        });
                });

            modelBuilder.Entity("GradDemo.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Hot Coffee",
                            Description = "Rich chocolate flavor with espresso and steamed milk",
                            ImageUrl = "https://cdn.grad-demo.com/items/mocha-flavor.jpg",
                            IsAvailable = true,
                            Name = "Mocha Flavor",
                            Price = 35.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Hot Coffee",
                            Description = "Smooth espresso with vanilla syrup and steamed milk",
                            ImageUrl = "https://cdn.grad-demo.com/items/vanilla-latte.jpg",
                            IsAvailable = true,
                            Name = "Vanilla Latte",
                            Price = 32.0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Hot Coffee",
                            Description = "Creamy latte with rich hazelnut flavor",
                            ImageUrl = "https://cdn.grad-demo.com/items/hazelnut-latte.jpg",
                            IsAvailable = true,
                            Name = "Hazelnut Latte",
                            Price = 34.0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Hot Coffee",
                            Description = "Espresso with vanilla syrup, milk, and caramel drizzle",
                            ImageUrl = "https://cdn.grad-demo.com/items/caramel-macchiato.jpg",
                            IsAvailable = true,
                            Name = "Caramel Macchiato",
                            Price = 38.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cold Coffee",
                            Description = "Chilled brewed coffee served over ice",
                            ImageUrl = "https://cdn.grad-demo.com/items/cold-coffee.jpg",
                            IsAvailable = true,
                            Name = "Cold Coffee",
                            Price = 25.0
                        },
                        new
                        {
                            Id = 6,
                            Category = "Cold Coffee",
                            Description = "Refreshing cold latte with strawberry syrup",
                            ImageUrl = "https://cdn.grad-demo.com/items/strawberry-latte.jpg",
                            IsAvailable = true,
                            Name = "Strawberry Latte",
                            Price = 36.0
                        },
                        new
                        {
                            Id = 7,
                            Category = "Cold Coffee",
                            Description = "Espresso shots chilled and served over ice",
                            ImageUrl = "https://cdn.grad-demo.com/items/iced-americano.jpg",
                            IsAvailable = true,
                            Name = "Iced Americano",
                            Price = 28.0
                        },
                        new
                        {
                            Id = 8,
                            Category = "Cold Coffee",
                            Description = "Smooth cold brewed coffee served chilled",
                            ImageUrl = "https://cdn.grad-demo.com/items/cold-brew.jpg",
                            IsAvailable = true,
                            Name = "Cold Brew",
                            Price = 30.0
                        },
                        new
                        {
                            Id = 9,
                            Category = "Tea",
                            Description = "Traditional green tea with fresh mint leaves",
                            ImageUrl = "https://cdn.grad-demo.com/items/moroccan-mint-tea.jpg",
                            IsAvailable = true,
                            Name = "Moroccan Mint Tea",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tea",
                            Description = "Classic black tea with bergamot orange flavor",
                            ImageUrl = "https://cdn.grad-demo.com/items/earl-grey.jpg",
                            IsAvailable = true,
                            Name = "Earl Grey",
                            Price = 18.0
                        },
                        new
                        {
                            Id = 11,
                            Category = "Tea",
                            Description = "Spiced tea with steamed milk and honey",
                            ImageUrl = "https://cdn.grad-demo.com/items/chai-latte.jpg",
                            IsAvailable = true,
                            Name = "Chai Latte",
                            Price = 26.0
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pastries",
                            Description = "Freshly baked butter croissant",
                            ImageUrl = "https://cdn.grad-demo.com/items/croissant.jpg",
                            IsAvailable = true,
                            Name = "Croissant",
                            Price = 15.0
                        },
                        new
                        {
                            Id = 13,
                            Category = "Pastries",
                            Description = "Rich chocolate muffin with chocolate chips",
                            ImageUrl = "https://cdn.grad-demo.com/items/chocolate-muffin.jpg",
                            IsAvailable = true,
                            Name = "Chocolate Muffin",
                            Price = 18.0
                        },
                        new
                        {
                            Id = 14,
                            Category = "Pastries",
                            Description = "Traditional scone with fresh blueberries",
                            ImageUrl = "https://cdn.grad-demo.com/items/blueberry-scone.jpg",
                            IsAvailable = true,
                            Name = "Blueberry Scone",
                            Price = 16.0
                        },
                        new
                        {
                            Id = 15,
                            Category = "Pastries",
                            Description = "Soft cinnamon roll with cream cheese frosting",
                            ImageUrl = "https://cdn.grad-demo.com/items/cinnamon-roll.jpg",
                            IsAvailable = true,
                            Name = "Cinnamon Roll",
                            Price = 22.0
                        },
                        new
                        {
                            Id = 16,
                            Category = "Special Drinks",
                            Description = "Rich and creamy hot chocolate",
                            ImageUrl = "https://cdn.grad-demo.com/items/hot-chocolate.jpg",
                            IsAvailable = true,
                            Name = "Hot Chocolate",
                            Price = 24.0
                        },
                        new
                        {
                            Id = 17,
                            Category = "Special Drinks",
                            Description = "Green tea powder with steamed milk",
                            ImageUrl = "https://cdn.grad-demo.com/items/matcha-latte.jpg",
                            IsAvailable = true,
                            Name = "Matcha Latte",
                            Price = 32.0
                        },
                        new
                        {
                            Id = 18,
                            Category = "Special Drinks",
                            Description = "Traditional strong Turkish coffee",
                            ImageUrl = "https://cdn.grad-demo.com/items/turkish-coffee.jpg",
                            IsAvailable = true,
                            Name = "Turkish Coffee",
                            Price = 20.0
                        });
                });

            modelBuilder.Entity("GradDemo.Models.ItemSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<double>("Multiplier")
                        .HasColumnType("float");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SizeId");

                    b.ToTable("ItemSize");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            Multiplier = 0.80000000000000004,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 1,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 1,
                            Multiplier = 1.2,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 1,
                            Multiplier = 1.5,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 2,
                            Multiplier = 0.80000000000000004,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 6,
                            ItemId = 2,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 7,
                            ItemId = 2,
                            Multiplier = 1.2,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 8,
                            ItemId = 2,
                            Multiplier = 1.5,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 9,
                            ItemId = 3,
                            Multiplier = 0.80000000000000004,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 10,
                            ItemId = 3,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 11,
                            ItemId = 3,
                            Multiplier = 1.2,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 12,
                            ItemId = 3,
                            Multiplier = 1.5,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 13,
                            ItemId = 4,
                            Multiplier = 0.80000000000000004,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 14,
                            ItemId = 4,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 15,
                            ItemId = 4,
                            Multiplier = 1.2,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 16,
                            ItemId = 4,
                            Multiplier = 1.5,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 17,
                            ItemId = 5,
                            Multiplier = 0.80000000000000004,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 18,
                            ItemId = 5,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 19,
                            ItemId = 5,
                            Multiplier = 1.2,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 20,
                            ItemId = 5,
                            Multiplier = 1.5,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 21,
                            ItemId = 6,
                            Multiplier = 0.80000000000000004,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 22,
                            ItemId = 6,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 23,
                            ItemId = 6,
                            Multiplier = 1.2,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 24,
                            ItemId = 6,
                            Multiplier = 1.5,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 25,
                            ItemId = 12,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 26,
                            ItemId = 13,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 27,
                            ItemId = 14,
                            Multiplier = 1.0,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 28,
                            ItemId = 15,
                            Multiplier = 1.0,
                            SizeId = 2
                        });
                });

            modelBuilder.Entity("GradDemo.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaptainId")
                        .HasColumnType("int");

                    b.Property<int>("CashierId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("WaiterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.HasIndex("CashierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.HasIndex("WaiterId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaptainId = 4,
                            CashierId = 2,
                            CustomerId = 9,
                            OrderDate = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TableId = 1,
                            Total = 142.0,
                            WaiterId = 6
                        },
                        new
                        {
                            Id = 2,
                            CaptainId = 5,
                            CashierId = 3,
                            CustomerId = 10,
                            OrderDate = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            TableId = 3,
                            Total = 198.0,
                            WaiterId = 7
                        },
                        new
                        {
                            Id = 3,
                            CaptainId = 4,
                            CashierId = 2,
                            CustomerId = 11,
                            OrderDate = new DateTime(2024, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TableId = 5,
                            Total = 76.0,
                            WaiterId = 8
                        },
                        new
                        {
                            Id = 4,
                            CaptainId = 5,
                            CashierId = 3,
                            CustomerId = 9,
                            OrderDate = new DateTime(2024, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TableId = 2,
                            Total = 124.0,
                            WaiterId = 6
                        },
                        new
                        {
                            Id = 5,
                            CaptainId = 4,
                            CashierId = 2,
                            CustomerId = 10,
                            OrderDate = new DateTime(2024, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TableId = 4,
                            Total = 45.0,
                            WaiterId = 7
                        });
                });

            modelBuilder.Entity("GradDemo.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPayed")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SizeId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPayed = true,
                            ItemId = 1,
                            OrderId = 1,
                            Quantity = 2,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 2,
                            IsPayed = true,
                            ItemId = 12,
                            OrderId = 1,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsPayed = true,
                            ItemId = 9,
                            OrderId = 1,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsPayed = true,
                            ItemId = 4,
                            OrderId = 2,
                            Quantity = 1,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 5,
                            IsPayed = true,
                            ItemId = 6,
                            OrderId = 2,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsPayed = true,
                            ItemId = 13,
                            OrderId = 2,
                            Quantity = 2,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsPayed = true,
                            ItemId = 5,
                            OrderId = 2,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 8,
                            IsPayed = false,
                            ItemId = 3,
                            OrderId = 3,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 9,
                            IsPayed = false,
                            ItemId = 15,
                            OrderId = 3,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 10,
                            IsPayed = true,
                            ItemId = 2,
                            OrderId = 4,
                            Quantity = 1,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 11,
                            IsPayed = true,
                            ItemId = 14,
                            OrderId = 4,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 12,
                            IsPayed = false,
                            ItemId = 16,
                            OrderId = 5,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 13,
                            IsPayed = false,
                            ItemId = 12,
                            OrderId = 5,
                            Quantity = 1,
                            SizeId = 2
                        });
                });

            modelBuilder.Entity("GradDemo.Models.ReturnedOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("ReturnedOrders");
                });

            modelBuilder.Entity("GradDemo.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cashier"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Captain"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Waiter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("GradDemo.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "S",
                            Description = "Small (8oz)"
                        },
                        new
                        {
                            Id = 2,
                            Code = "M",
                            Description = "Medium (12oz)"
                        },
                        new
                        {
                            Id = 3,
                            Code = "L",
                            Description = "Large (16oz)"
                        },
                        new
                        {
                            Id = 4,
                            Code = "X",
                            Description = "Extra Large (20oz)"
                        });
                });

            modelBuilder.Entity("GradDemo.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Main Hall - Window View"
                        },
                        new
                        {
                            Id = 2,
                            Area = "Main Hall - Center"
                        },
                        new
                        {
                            Id = 3,
                            Area = "Main Hall - Quiet Corner"
                        },
                        new
                        {
                            Id = 4,
                            Area = "Outdoor Terrace - Garden"
                        },
                        new
                        {
                            Id = 5,
                            Area = "Outdoor Terrace - Street View"
                        },
                        new
                        {
                            Id = 6,
                            Area = "VIP Lounge - Private"
                        },
                        new
                        {
                            Id = 7,
                            Area = "VIP Lounge - Family"
                        },
                        new
                        {
                            Id = 8,
                            Area = "Smoking Area - Outdoor"
                        },
                        new
                        {
                            Id = 9,
                            Area = "Reading Corner"
                        },
                        new
                        {
                            Id = 10,
                            Area = "Business Meeting Area"
                        });
                });

            modelBuilder.Entity("GradDemo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "manager@mochacafe.com",
                            Name = "Cafe Manager",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000001",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "ahmed.cashier@mochacafe.com",
                            Name = "Ahmed Cashier",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000002",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "mona.cashier@mochacafe.com",
                            Name = "Mona Cashier",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000003",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "samir.captain@mochacafe.com",
                            Name = "Captain Samir",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000004",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            Email = "rania.captain@mochacafe.com",
                            Name = "Captain Rania",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000005",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            Email = "tarek.barista@mochacafe.com",
                            Name = "Barista Tarek",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000006",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 7,
                            Email = "nadia.barista@mochacafe.com",
                            Name = "Barista Nadia",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000007",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 8,
                            Email = "karim.barista@mochacafe.com",
                            Name = "Barista Karim",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000008",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 9,
                            Email = "ali.customer@email.com",
                            Name = "Regular Customer Ali",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000009",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 10,
                            Email = "sara.customer@email.com",
                            Name = "Customer Sara",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000010",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 11,
                            Email = "omar.customer@email.com",
                            Name = "Customer Omar",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWWKzOyYcpm02EZvXQvtSWGoNo/kFwiYgsJZL5APdqOcx/6ZGytrFrgyb88l0mzA==",
                            Phone = "+201000000011",
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("GradDemo.Models.Bill", b =>
                {
                    b.HasOne("GradDemo.Models.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GradDemo.Models.CancelledOrder", b =>
                {
                    b.HasOne("GradDemo.Models.User", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CancelledBy");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GradDemo.Models.ItemSize", b =>
                {
                    b.HasOne("GradDemo.Models.Item", "Item")
                        .WithMany("ItemSizes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.Size", "Size")
                        .WithMany("ItemSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("GradDemo.Models.Order", b =>
                {
                    b.HasOne("GradDemo.Models.User", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.User", "Waiter")
                        .WithMany()
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("Cashier");

                    b.Navigation("Customer");

                    b.Navigation("Table");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("GradDemo.Models.OrderItem", b =>
                {
                    b.HasOne("GradDemo.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("GradDemo.Models.ReturnedOrder", b =>
                {
                    b.HasOne("GradDemo.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradDemo.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GradDemo.Models.User", b =>
                {
                    b.HasOne("GradDemo.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GradDemo.Models.Item", b =>
                {
                    b.Navigation("ItemSizes");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GradDemo.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GradDemo.Models.Size", b =>
                {
                    b.Navigation("ItemSizes");
                });
#pragma warning restore 612, 618
        }
    }
}
